image: node:latest

all_tests:
	script:
		- npm install
   
deploy:
	stage:deploy
	script:
		- eval $(ssh-agent -s)
		- ssh-add <(echo "$GITLAB_DEPLOY_KEY")
		- mkdir -p ~/.ssh
		- ssh orcas@makerforce.io "touch Iwashere"